### ISSUE TITLE
Potentially severe security flaw

### ISSUE THREAD

**Issue by MSC-Secura** [b2evolution/b2evolution#114]
Hi,

It seems this project is at the very best in maintenance-only mode, but I would still like to report a serious security issue. I have tried using the e-mail contact form on the official site, but that doesn't seem to work any more. Is there some way I can contact you privately to responsibly disclose this?

**Comment by fplanque** [comment]
sec22 (at) b2evolution.net 
Thanks.

**Comment by keithbowes** [comment]
> It seems this project is at the very best in maintenance-only mode

Which is a good thing.  It was getting bigger and bigger for ages, so I started my own fork to try to slim it down.  I haven't had much luck doing that and most of my work has just been trying to fix deprecation warnings (today's deprecation warnings are tomorrow's errors) for each new version of PHP.  Currently, I'm working on fixing all the warnings about dynamic properties being deprecated in PHP 8.2, and there are so many of them.

Though, I did backport the fix for this security issue and bumped up the required version of PHP to PHP 7 instead of creating an implementation for 15-year-old versions of PHP like the upstream project did.  I mean, it would be nice to support as many versions of PHP as possible, but there comes a time when the cost is so much greater than the benefit.
