### ISSUE TITLE
How can you adjust dofollow comments

### ISSUE THREAD

**Issue by AlexL777** [b2evolution/b2evolution#16]
Hello Developers,

I have a question namely how can you have all the external links as DoFollow in the comments? Currently, I see at b2evo 6.7.0 that the outbound links are provided with the nofollow attribute.

In a review in the BackOffice I can on the fly do not find this option. Can you help me maybe?

Thank you in advance.

**Comment by mgsolipa** [comment]
@AlexL777 you can enable/disable the **nofollow** option for Posts and Comments on the **Auto Links plugin** settings (http://plugins.b2evolution.net/plugins-autolinks-plugin). 

There is no "dofollow", just adding `rel="nofollow"` or not to the automatically generated links.

For further questions, please use the Forums (http://forums.b2evolution.net/) due to that's our main support channel.

Thanks.

**Comment by fplanque** [comment]
The nofollows may also be added by the basic antispam plugin.

**Comment by AlexL777** [comment]
Thank you, and I have already found it :) So I thought, there must be working on DoFollow and behold, it works.

**Comment by GauravRaj1** [comment]
Thank you sir for sharing this great information.

Regards
Gaurav
Digital Marketing Executive
http://www.techstack.in
