### ISSUE TITLE
PHP5.2.11 Strict Standards: Declaration of Country::dbexists() should be compatible with that of DataObject::dbexists() in  inc/regional/model/_country.class.php on line 146

### ISSUE THREAD

**Issue by hhren1984** [b2evolution/b2evolution#24]
I try to check the code, it seems no problem, I don't know why.

**Comment by keithbowes** [comment]
Does that occur in other versions of PHP 5.2.x?  Perhaps it's just a bug in that version.

Personally, I'm not sure why b2evolution is still supporting PHP 5.2.x, a version that's been EOL for several years, anyway.  I thought maybe it was parity with other similar systems, but it turns out the requirement for Drupal is PHP 5.5.9+ and the requirement for WordPress is PHP 5.6+, so that can't be the reason.  Maybe @fplanque can clarify.

**Comment by fplanque** [comment]
Because many users still use PHP 5.2.x and so far we didn't find any issues that made 5.2 difficult to support. In this case I do not think it's specific to PHP 5.2 but only to strict standards.

**Comment by fplanque** [comment]
Fixed by https://github.com/b2evolution/b2evolution/commit/889e1c7916db3efd8cf49b26724086bbe39bc1c3
