### ISSUE TITLE
Need for an App 

### ISSUE THREAD

**Issue by hgkamath** [b2evolution/b2evolution#4]
I recommend the use of Apache Cordova, which using HTML5/javascript allows for building apps for many different smartphones Android, FirefoxOS, Iphone, Blackberry etc . Cordova enables to target many platforms at once and simultaneously eliminate the need to know any sort of specific native programming for the host environment, other than some basic building-IDEs and choosing cordova plugins which abtract away platform differences for various features, ex plugins for device_info/location/push notifications etc.     

A app does more than opening in a browser, such as caching and offline reading/editting.

**Comment by fplanque** [comment]
@hgkamath That makes sense, especially the offline drafting, IMHO.

Another useful feature would be donwloading of comments awaiting for moderation with possible offline moderation and sync as soon as possible.

We don't have the resources to develop this within our current team though. If someones wants to develop this we'll be happy to promote it.

**Comment by keithbowes** [comment]
Hmm.  This sounds like something for a [blogging client](http://b2evolution.net/man/desktop-blogging-tools-1) rather than something that should be added to b2evolution itself.  Both b2evolution and WordPress support the same MetaWeblog XML-RPC API to do this stuff.  That is, the low-level framework is already there.  There are already third-party apps that use it (I use a [modified version](http://github.com/keithbowes/mtsend) of Scott Yang's mtsend Python script (which ceased to work correctly in Python 2.7) to post and edit my blog posts, personally; certainly, there are similar clients for mobile platforms).
