### ISSUE TITLE
Table 'b2evolution.evo_coll_settings' doesn't exist(Errno=1146)

### ISSUE THREAD

**Issue by awveale** [b2evolution/b2evolution#43]
I am using a fresh install of b2evolution-6.8.7-stable-2017-02-14

On the user profile, Notifications page I get "Table 'b2evolution.evo_coll_settings' doesn't exist(Errno=1146)"

It appears to be in the file inc/collections/model/_blogcache.class.php

There is an existing table, b2evolution.coll_settings, which appears to have the appropriate structure.  Perhaps a recent database schema update did not get its changes put into this file.

Replacing "evo_coll_settings" with "coll_settings" in lines 537 and 538 of that file appears to fix the error.

**Comment by keithbowes** [comment]
Hmm.  That seems to be [someone](https://github.com/b2evolution/b2evolution/blame/master/inc/collections/model/_blogcache.class.php#L537)'s brainfart, hardcoding in the default evo_ prefix instead of using the T_ notation.  I on the other hand, use the default evo_ prefix, so I do have an evo_coll_settings table.

**Comment by fplanque** [comment]
We'll fix this by using `T_` instead of `evo_`.

**Comment by fplanque** [comment]
Fixed in https://github.com/b2evolution/b2evolution/commit/a531b35f6eb89f3b8833e150134841aff9f526c5
